### ISSUE TITLE
Failed to install openresty yum package

### ISSUE THREAD

**Issue by spacewander** [openresty/openresty-packaging#79]
Get this error:
```
Downloading packages:
https://openresty.org/package/centos/7/x86_64/openresty-debug-1.19.9.1-1.el7.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=openresty clean metadata
Trying other mirror.
```

run `yum --enablerepo=openresty clean metadata` doesn't solve the problem.

**Comment by cppcoffee** [comment]
Thanks for reporting, this may be a problem with the open source repository index, we' ll check it out.

**Comment by cppcoffee** [comment]
Hi @spacewander , this is a CDN caching issue that we have fixed.

**Comment by spacewander** [comment]
Thanks for your fast response! Solved.

**Comment by andymurn** [comment]
I'm stilling seeing this same issue and have been during the last few days. It is affecting our image building in all the AWS regions that I tried.
Running `yum --enablerepo=openresty clean metadata` as the error suggests doesn't resolve the problem like the other commenter stated.

@cppcoffee - Could you confirm that the issue is still resolved.

**Comment by xiaocang** [comment]
@andymurn could you provide the distribution (like amazonlinux 2) you used?

**Comment by JoeARO** [comment]
👋  Hi there I am seeing the same issue in my project:
```bash
https://openresty.org/package/rhel/7/x86_64/openresty-pcre-8.44-1.el7.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=openresty clean metadata
```
Wondering if it is also a cdn issue?

**Comment by zhuizhuhaomeng** [comment]
please try again

**Comment by JoeARO** [comment]
> please try again

Thanks for the swift reply @zhuizhuhaomeng, that has worked now thank you!

**Comment by andymurn** [comment]
> @andymurn could you provide the distribution (like amazonlinux 2) you used?

Red Hat Enterprise Linux 7 (RHEL7) was what was causing the issue. I just tested it out after @zhuizhuhaomeng updated it and it now works! Thank you!
